export type User = {
  id: string;
  name: string;
  email: string;
  role: string;
  status?: string;
  emailVerified?: boolean;
  avatarUrl?: string | null;
  phone?: string | null;
  lastLoginAt?: string | null;
  settings?: Settings;
};
export type Settings = { theme?: 'light' | 'dark'; notificationsEnabled?: boolean; timezone?: string; language?: string };
export type OrganizationMember = { id: string; role: string; user: User };
export type Organization = {
  id: string;
  name: string;
  logoUrl?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  address?: string | null;
  timezone?: string;
  currency?: string;
  language?: string;
  primaryColor?: string;
  secondaryColor?: string;
  appearance?: string;
  members?: OrganizationMember[];
};
export type Plan = { id: string; name: string; slug: string; description: string; priceMonthly: number; priceYearly: number; features: string };
export type Subscription = { id: string; plan?: Plan } | null;
export type Notification = { id: string; title: string; message: string; isRead?: boolean; createdAt?: string; type?: string };
export type FileRecord = { id: string; originalName: string; mimeType: string; path?: string; sizeBytes?: number; createdAt?: string; storedName?: string };
export type ActivityLog = { id: string; action: string; entityType: string; entityId?: string | null; createdAt: string; metadata?: string | null };
export type Overview = { users: number; subscriptions: number; activityLogs: number } | null;
export type AdminMetric = { totalUsers: number; activeUsers: number; organizations: number; subscriptions: number; revenue: number; roles: number; permissions: number; storageBytes: number };
export type AdminDashboard = { metrics: AdminMetric; recentActivity: ActivityLog[]; growth: Array<{ createdAt: string; _count: { id: number } }> };
export type RolePermission = { id: string; permission: { id: string; code: string; resource: string; action: string; description?: string | null } };
export type RoleRecord = { id: string; name: string; slug: string; description?: string | null; isSystem?: boolean; permissions?: RolePermission[]; assignments?: Array<{ id: string; userId: string }> };
export type PermissionRecord = { id: string; code: string; resource: string; action: string; description?: string | null };
export type AdminSetting = { id: string; key: string; value: string };
export type Guardian = { id: string; name: string; relationship: string; phone?: string | null; email?: string | null; address?: string | null; occupation?: string | null };
export type StudentDocument = { id: string; documentName: string; fileUrl: string; uploadedAt: string };
export type StudentTransfer = { id: string; previousBranchId?: string | null; newBranchId?: string | null; previousClassRoomId?: string | null; newClassRoomId?: string | null; transferDate: string; reason?: string | null };
export type AttendanceStatus = 'PRESENT' | 'ABSENT' | 'LATE' | 'LEAVE';
export type AttendanceRecord = {
  id: string;
  date: string;
  status: AttendanceStatus;
  remarks?: string | null;
  studentId: string;
  student?: Student;
  branchId?: string | null;
  classRoomId?: string | null;
  sectionId?: string | null;
  markedBy?: string | null;
  createdAt?: string;
  updatedAt?: string;
};
export type AttendanceSummary = {
  id?: string;
  month?: number;
  year?: number;
  totalDays: number;
  presentDays: number;
  absentDays: number;
  lateDays: number;
  leaveDays: number;
  percentage: number;
};
export type LeaveRequest = {
  id: string;
  studentId: string;
  dateFrom: string;
  dateTo: string;
  reason: string;
  status?: string;
  approvedBy?: string | null;
  student?: Student;
  createdAt?: string;
};
export type FeeStructure = {
  id: string;
  name: string;
  amount: number;
  frequency: 'MONTHLY' | 'QUARTERLY' | 'YEARLY' | 'ONE_TIME';
  description?: string | null;
  status: string;
  branchId?: string | null;
  academicYearId?: string | null;
  programId?: string | null;
  classRoomId?: string | null;
};
export type FeeAssignment = {
  id: string;
  amount: number;
  discountAmount: number;
  finalAmount: number;
  startDate: string;
  endDate?: string | null;
  status: string;
  feeStructure?: FeeStructure;
};
export type FeePayment = {
  id: string;
  amount: number;
  paymentDate: string;
  paymentMethod: 'CASH' | 'BANK' | 'ONLINE';
  referenceNumber?: string | null;
  receivedBy?: string | null;
  remarks?: string | null;
  receiptNumber: string;
  studentId: string;
};
export type FeeInvoice = {
  id: string;
  invoiceNumber: string;
  amount: number;
  dueDate: string;
  status: 'PAID' | 'PARTIAL' | 'UNPAID' | 'OVERDUE' | string;
  studentId: string;
};
export type Exam = { id: string; name: string; examType: 'MONTHLY' | 'QUARTERLY' | 'HALF_YEARLY' | 'ANNUAL' | 'FINAL'; startDate: string; endDate: string; status: string; branchId?: string | null; academicYearId?: string | null };
export type ExamSubject = { id: string; subjectId: string; totalMarks: number; passingMarks: number };
export type ExamResult = { id: string; examId: string; studentId: string; subjectId: string; obtainedMarks: number; grade: string; remarks?: string | null; student?: Student };
export type ResultCard = { id: string; studentId: string; examId: string; totalMarks: number; obtainedMarks: number; percentage: number; grade: string; position?: number | null; generatedAt?: string };
export type CertificateTemplate = { id: string; name: string; type: string; templateContent: string };
export type Certificate = { id: string; certificateNumber: string; issueDate: string; title: string; description?: string | null; issuedBy?: string | null; status: string; studentId: string; template?: CertificateTemplate | null; verification?: { verificationCode: string; verifiedAt?: string | null; ipAddress?: string | null } | null };
export type FinanceAccount = { id: string; accountCode: string; accountName: string; accountType: 'ASSET' | 'LIABILITY' | 'EQUITY' | 'INCOME' | 'EXPENSE'; openingBalance: number; currentBalance: number; status: string };
export type FinanceTransactionLine = { id: string; accountId: string; debit: number; credit: number; remarks?: string | null; account?: FinanceAccount };
export type FinanceTransaction = { id: string; voucherNumber: string; transactionDate: string; description: string; totalAmount: number; lines?: FinanceTransactionLine[] };
export type FinanceExpense = { id: string; amount: number; paymentMethod: 'CASH' | 'BANK' | 'ONLINE'; paidTo: string; invoiceNumber?: string | null; expenseDate: string; remarks?: string | null; category?: { id: string; name: string } };
export type FinanceDonation = { id: string; donorName: string; phone?: string | null; email?: string | null; donationType: 'ZAKAT' | 'SADAQAH' | 'LILLAH' | 'GENERAL' | 'FITRANA' | 'QURBANI' | 'SPONSORSHIP'; amount: number; paymentMethod: 'CASH' | 'BANK' | 'ONLINE'; receiptNumber: string; purpose?: string | null; date: string };
export type HrDepartment = { id: string; name: string; description?: string | null };
export type HrDesignation = { id: string; title: string; description?: string | null; department?: HrDepartment };
export type Employee = {
  id: string;
  employeeNumber: string;
  firstName: string;
  lastName: string;
  fatherName?: string | null;
  gender?: string | null;
  dob?: string | null;
  cnic?: string | null;
  phone?: string | null;
  email?: string | null;
  address?: string | null;
  photo?: string | null;
  employmentType: string;
  joiningDate: string;
  contractEndDate?: string | null;
  status: string;
  qualification?: string | null;
  experience?: string | null;
  emergencyContact?: string | null;
  bankName?: string | null;
  accountNumber?: string | null;
  basicSalary: number;
  department?: HrDepartment | null;
  designation?: HrDesignation | null;
};
export type EmployeeAttendance = { id: string; employeeId: string; attendanceDate: string; checkIn?: string | null; checkOut?: string | null; status: string; remarks?: string | null; employee?: Employee };
export type HrLeave = { id: string; employeeId: string; leaveType: string; startDate: string; endDate: string; reason: string; status: string; approvedBy?: string | null; employee?: Employee };
export type Payroll = { id: string; employeeId: string; month: number; year: number; basicSalary: number; allowances: number; deductions: number; overtime: number; bonus: number; netSalary: number; paymentStatus: string; paymentMethod?: string | null; paymentDate?: string | null; employee?: Employee; salarySlip?: { id: string; slipNumber: string; pdfPath?: string | null } | null };
export type InventoryCategory = { id: string; name: string; description?: string | null };
export type Asset = { id: string; assetCode: string; name: string; description?: string | null; purchaseDate: string; purchasePrice: number; currentValue: number; condition: string; location?: string | null; assignedTo?: string | null; status: string; category?: InventoryCategory; maintenance?: Array<{ id: string; issue: string; cost: number; date: string; status: string }> };
export type InventoryItem = { id: string; name: string; sku: string; quantity: number; minimumStock: number; unit: string; description?: string | null; category?: InventoryCategory; movements?: Array<{ id: string; type: string; quantity: number; reference?: string | null; date: string }> };
export type Supplier = { id: string; name: string; phone?: string | null; email?: string | null; address?: string | null };
export type Purchase = { id: string; invoiceNumber: string; purchaseDate: string; totalAmount: number; paymentStatus: string; supplier?: Supplier; items?: Array<{ id: string; quantity: number; unitPrice: number; item?: InventoryItem }> };
export type MaintenanceRecord = { id: string; assetId: string; issue: string; cost: number; date: string; status: string; remarks?: string | null; asset?: Asset };
export type Student = {
  id: string;
  registrationNumber: string;
  admissionNumber?: string | null;
  fullName: string;
  fatherName?: string | null;
  grandfatherName?: string | null;
  dateOfBirth?: string | null;
  gender?: string | null;
  photo?: string | null;
  phone?: string | null;
  guardianPhone?: string | null;
  email?: string | null;
  address?: string | null;
  city?: string | null;
  province?: string | null;
  branchId?: string | null;
  departmentId?: string | null;
  programId?: string | null;
  classRoomId?: string | null;
  sectionId?: string | null;
  academicYearId?: string | null;
  status: 'ACTIVE' | 'GRADUATED' | 'LEFT' | 'SUSPENDED';
  admissionDate: string;
  guardian?: Guardian | null;
  documents?: StudentDocument[];
  transfers?: StudentTransfer[];
  attendanceRecords?: AttendanceRecord[];
  attendanceSummary?: AttendanceSummary | null;
  feeAssignments?: FeeAssignment[];
  feePayments?: FeePayment[];
  feeInvoices?: FeeInvoice[];
  examResults?: ExamResult[];
  resultCards?: ResultCard[];
  certificates?: Certificate[];
  financeAccounts?: FinanceAccount[];
};
