export type User = {
  id: string;
  name: string;
  email: string;
  role: string;
  status?: string;
  emailVerified?: boolean;
  avatarUrl?: string | null;
  phone?: string | null;
  lastLoginAt?: string | null;
  settings?: Settings;
};
export type Settings = { theme?: 'light' | 'dark'; notificationsEnabled?: boolean; timezone?: string; language?: string };
export type OrganizationMember = { id: string; role: string; user: User };
export type Organization = {
  id: string;
  name: string;
  logoUrl?: string | null;
  contactEmail?: string | null;
  contactPhone?: string | null;
  address?: string | null;
  timezone?: string;
  currency?: string;
  language?: string;
  primaryColor?: string;
  secondaryColor?: string;
  appearance?: string;
  members?: OrganizationMember[];
};
export type Plan = { id: string; name: string; slug: string; description: string; priceMonthly: number; priceYearly: number; features: string };
export type Subscription = { id: string; plan?: Plan } | null;
export type Notification = { id: string; title: string; message: string; isRead?: boolean; createdAt?: string; type?: string };
export type FileRecord = { id: string; originalName: string; mimeType: string; path?: string; sizeBytes?: number; createdAt?: string; storedName?: string };
export type ActivityLog = { id: string; action: string; entityType: string; entityId?: string | null; createdAt: string; metadata?: string | null };
export type Overview = { users: number; subscriptions: number; activityLogs: number } | null;
export type AdminMetric = { totalUsers: number; activeUsers: number; organizations: number; subscriptions: number; revenue: number; roles: number; permissions: number; storageBytes: number };
export type AdminDashboard = { metrics: AdminMetric; recentActivity: ActivityLog[]; growth: Array<{ createdAt: string; _count: { id: number } }> };
export type RolePermission = { id: string; permission: { id: string; code: string; resource: string; action: string; description?: string | null } };
export type RoleRecord = { id: string; name: string; slug: string; description?: string | null; isSystem?: boolean; permissions?: RolePermission[]; assignments?: Array<{ id: string; userId: string }> };
export type PermissionRecord = { id: string; code: string; resource: string; action: string; description?: string | null };
export type AdminSetting = { id: string; key: string; value: string };
